### ISSUE TITLE
Error decoding unicode char

### ISSUE THREAD

**Issue by dobromyslov** [asheiduk/factorio-blueprint-decoder#4] opened 2021-03-11 19:29 UTC
```
Traceback (most recent call last):
  File "D:\tmp\factorio\decode.py", line 2647, in <module>
    json.dump(library, sys.stdout, indent=4, sort_keys=True, ensure_ascii=False)
  File "C:\Python39\lib\json\__init__.py", line 180, in dump
    fp.write(chunk)
  File "C:\Python39\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2260' in position 1: character maps to <undefined>
```

**Comment by dobromyslov** [comment] 2021-03-11 19:31
[blueprint-storage.zip](https://github.com/asheiduk/factorio-blueprint-decoder/files/6125512/blueprint-storage.zip)

**Comment by asheiduk** [comment] 2021-03-12 18:04
The problem is that you are using an 8bit encoding (`cp1251`) which does not support all characters needed by the output. The culprit at hand is `≠` (`\u2260`) which is used quite often in circuit conditions.

As a *short-term* solution you can temporary set the encoding to `UTF-8` before running one of the scripts. In a Unix shell you can use something like this:

    export LANG=en_US.UTF-8

in a Windows Shell this should work (untested):

    set LANG=en_US.UTF-8

I'll think about how to fix *all* involved script, not just `decode`.

**Comment by asheiduk** [comment] 2021-03-28 12:59
I've pushed a bugfix into the branch `bugfix/utf8-encoding`. Can you test it?

**Comment by asheiduk** [comment] 2021-05-18 16:10
Closing due to timeout.

**Closed as completed by asheiduk** 2021-05-18 16:10 UTC
Labels: bug
