### ISSUE TITLE
Please add support for game version 1.1-Stable (1.1.21) 

### ISSUE THREAD

**Issue by click0** [asheiduk/factorio-blueprint-decoder#2] opened 2021-02-09 18:15 UTC
In Steam version of the game 1.1-Stable has already become 1.1.21.

We get the following error:
```
decode blueprint-storage.dat > my-bps1.json
Traceback (most recent call last):
  File "./decode", line 2405, in <module>
    library = parse_blueprint_library(PrimitiveStream(f))
  File "./decode", line 2144, in parse_blueprint_library
    stream.expect(0x00, 0x00)
  File "./decode", line 278, in expect
    raise ParseError(f"expected {expected:#04x} but got {actual:#04x} at position {position} ({position:#x})")
__main__.ParseError: expected 0x00 but got 0x2c at position 11034 (0x2b1a)
```

Here is the link of the [forum post](https://forums.factorio.com/viewtopic.php?p=534215#p534215) to someone else's [blueprint-storage.dat file](https://forums.factorio.com/download/file.php?id=66946). 
Our errors are similar.

**Comment by click0** [comment] 2021-02-10 04:58
There is a similar error with [this file](https://github.com/Luchanso/factorio-server/blob/master/blueprint-storage.dat). 
This file is two years old, and then there was still a branch of the game - 0.16.x. 

```
$ ./decode blueprint-storage-2.dat > my-bps1.json
Traceback (most recent call last):
  File "./decode", line 2411, in <module>
    library = parse_blueprint_library(PrimitiveStream(f))
  File "./decode", line 2144, in parse_blueprint_library
    stream.expect(0x00)
  File "./decode", line 284, in expect
    raise ParseError(f"expected {expected:#04x} but got {actual:#04x} at position {position} ({position:#x})")
__main__.ParseError: expected 0x00 but got 0x10 at position 8 (0x8)
```

**Comment by asheiduk** [comment] 2021-02-11 17:20
> Here is the link of the [forum post](https://forums.factorio.com/viewtopic.php?p=534215#p534215) to someone else's [blueprint-storage.dat file](https://forums.factorio.com/download/file.php?id=66946).
> Our errors are similar.

Don't think so. The file is from the unstable version 1.1.15.0. I don't support unstable versions but nevertheless patched the tool to accept it as the 1.1.19 format. It gave up here:

```
[73] library slot: used
blueprint 'BAEarlyGameMall' (@0x17c7398)
Traceback (most recent call last):
  File "./decode", line 2502, in <module>
    library = parse_blueprint_library(PrimitiveStream(f))
  File "./decode", line 2261, in parse_blueprint_library
    parse_library_objects(stream, global_index, book_item, library_version)
  File "./decode", line 1962, in parse_library_objects
    handler_result = handler(stream, index, library_version)
  File "./decode", line 2284, in parse_blueprint
    stream.expect(0x00, 0x00)
  File "./decode", line 298, in expect
    raise ParseError(f"expected {expected:#04x} but got {actual:#04x} at position {position} ({position:#x})")
__main__.ParseError: expected 0x00 but got 0x01 at position 24933289 (0x17c73a9)
```

Note the file position (~25M of 35M) and that the traceback ends with `parse_blueprint[...]expect`. This is not comparable with your first traceback which indicates a position at the beginning of the file and a traceback with `parse_blueprint_library[...]expect`. That position at the beginning has to do with some state concerning the complete library -- not related to a specific bluepriint.

My traceback also indicates that the file contains stuff from removed mods. Currently I don't support this also although some patches are in the queue.

**Comment by asheiduk** [comment] 2021-02-11 17:23
> There is a similar error with [this file](https://github.com/Luchanso/factorio-server/blob/master/blueprint-storage.dat).
> This file is two years old, and then there was still a branch of the game - 0.16.x.

I don't support experimental versions - just stable versions. The tool does not enforce this so you can use it as long as the experimental version does not change the file format. But 0.16.0 is really out of scope.

**Comment by asheiduk** [comment] 2021-02-11 17:26
Can you test the "Work In Progress" (WIP) branch `feature/support-1.1.19`? AFAIK the file format did not change after 1.1.19 so 1.1.21 might work out of the box.

**Comment by click0** [comment] 2021-02-11 22:01
On the `feature/support-1.1.19` branch: 
```
$ ./decode -d blueprint-storage-my.dat
file: blueprint-storage-my.dat
version: 1.1.21.0
used prototypes: 74
...
Traceback (most recent call last):
  File "./decode", line 2501, in <module>
    library = parse_blueprint_library(PrimitiveStream(f))
  File "./decode", line 2240, in parse_blueprint_library
    stream.expect(0x00, 0x00)
  File "./decode", line 297, in expect
    raise ParseError(f"expected {expected:#04x} but got {actual:#04x} at position {position} ({position:#x})")
__main__.ParseError: expected 0x00 but got 0x0e at position 11164 (0x2b9c)
```

**Comment by asheiduk** [comment] 2021-02-11 23:29
>   File "./decode", line 2240, in parse_blueprint_library
>     stream.expect(0x00, 0x00)
>   File "./decode", line 297, in expect
>     raise ParseError(f"expected {expected:#04x} but got {actual:#04x} at position {position} ({position:#x})")
> __main__.ParseError: expected 0x00 but got 0x0e at position 11164 (0x2b9c)

Well yes, we are back to square one: This is comparable to your initial traceback and I've already mentioned in #1 that I need an example for that case. The linked files don't show *this* issue but have other issues. 

Also note that this traceback has most likely nothing to do with the title -- support for v1.1.21 -- since the expectation in the code is also broken in rare cases in v1.0.0.

**Comment by click0** [comment] 2021-02-11 23:55
[Example file](https://mega.nz/file/Q9QWCRbR#6tP7fhEo-5aTPx7UVCrtMF8d0rivGT9_3KngosdOgqM).
And `magic` word - ```bf83yr62cf89zs```

**Comment by asheiduk** [comment] 2021-02-15 15:46
The bad news: The unknown byte before the first blueprint is still unknown. The good news: It doesn't affect
the parsing of the following content so I can just ignore it.

I have also implemented a new option: `-s|--skip-bad` which skips unparsable blueprints and continues parsing. 
With this option I've analysed the "Example file". Here are the findings:


- `Science` --> `1K 0.17 Science v2`

	This blueprint contains two train schedules but there are no trains. The first schedules reference
	a locomotive with id `0`, the second does so twice! Locomotives cannot have `0` ids. Given the label
	`...0.17...` I think this is an old blueprint where some update of the game did not convert the
	blueprint properly.

	Solution: You have to export this blueprint as a string, reimport it and replace the old one. That worked for me.


- `2-4 Train Sub-factories` --> `bbq 2700spm Raffinerie 1.1`

	Some cargo-wagons are colored -- this cannot be done in the vanilla game. On top of that the colors
	are not only RGB but RGBA -- the alpha channel cannot be set in-game even for locomotives!

	Solution: I've updated the code for cargo-wagon. Other wagon types seem to accept no colors.

- `Book of Squirrel` --> unnamed blueprint between `Armor & Combat Gear Mall - from Plates – BobAAAces` and
	`Balanced 6 Station Unloader`

	This is still stored in v1.0.0 format because required mods have been deinstalled -- guessing
	"Ultimate Belts" and "Longer Underground Belt (Aligned)" and at least a third one with an entity
	`container/teleportation-teleprovider`. I'v tried "Teleportation_Redux" but that didn't work.

	The blueprint decoder did not support blueprints with removed mods in the previous version.
	Using some experimental code the error crops up for a standard active provider chest. 
	The error was due to using the wrong version for decoding stuff.

	Solution: I've fixed the version mismatch and refined the experimental "removed mods" code.

- `Oil Processing + Products` --> `bbq 2700spm Raffinerie 1.1`

	Same problems with cargo-wagons as above.

	Solution: fixed code

- `Smelting` --> <unnamed> #6 and 12 blueprints in `Smelting (Perfect)`

	Some furnaces have a "direction" value. This is not possible in the vanilla game. 
	
	Solution: I've fixed the code to ignore the direction since the export format does not write these values too.

- `[Rails] Logistic Train` --> <unnamed> #5 (before `Artillery Spot`)

	This one contains trains with temporary stops which the decoder did not support yet.

	Be aware that the game support for temporary stops also has some edges:

	- After stamping down the blueprint the schedule contains temporary stops but the temporary stops 
		  point to the *original* coordinates, not to a coordinate relative to the new location.

	- The export string for the blueprint also contains no coordinates so a reimport just contains "invalid" 
		temporary stops. These stops must be cleared by hand.

		This obviously also affects the decoder.

	Solution: I've fixed the code to parse temporary train stops.

- `[Rails] Logistic Train` --> `Service Station Demo (Creative Mod + GhostScanner)`

	Same problems with cargo-wagons as above.

	Solution: fixed code



So: Your have to cleanup one blueprint yourself, the rest can be handled by the new code in (commit 6b2ba6a).

On the very title of this issue: None of these problems are specific for v1.1.21 (or v1.1.19). The new code 
has tests for 1.1.19. Manual tests with 1.1.21 did (and dissecting this file) showed no differences in the 
file format. I think that's good enough for now.

**Comment by click0** [comment] 2021-02-16 15:50
I am grateful for such a titanic work.
I will think about how to add BP as json to git.

**Comment by asheiduk** [comment] 2021-02-16 16:08
> I am grateful for such a titanic work.

Thanks :-)



> I will think about how to add BP as json to git.

That's what I do, too. But my library is much smaller and I'm pondering about splitting the big JSON into smaller parts (e.g. one directory per book, one file per blueprint, planner...). That way changes could be tracked much more precise and with much less space. Since the output format is JSON I think I will use [`jq`] as a postprocessor.

[`jq`]: https://stedolan.github.io/jq/

**Closed as completed by asheiduk** 2021-02-16 16:08 UTC
Labels: bug

**Comment by asheiduk** [comment] 2022-04-11 20:59
@click0 FYI: The remaining bug `Science --> 1K 0.17 Science v2` seems to be the same as issue #9. Although I still cannot reproduce the issue from scratch the decoder supports that situation now.

**Comment by click0** [comment] 2022-04-11 21:43
Thanks.
These errors don't apply to me. 
I solved my problems with converting old BPs.
